### ISSUE TITLE
数组增删变动导致Iphone 6S 6P 7上定位为absolute的图片定位错乱

### ISSUE THREAD

**Issue by maple5233** [wepyjs/wepy#119]
例如我有一堆定位到**长短不一**的框框右上角的image形式的X 而这些框框构成了一个列表：
![image](https://cloud.githubusercontent.com/assets/16346984/25603117/c557b8fa-2f2b-11e7-8912-27d92fb18918.png)

CSS代码如下
```css
.choosed-food {
    height: 105rpx;
    line-height: 105rpx;
    padding: 15rpx 35rpx;
    margin-right: 25rpx;
    border: @1px-border;
    display: inline;
    position: relative;
}
.choosed-food .cross {
    width: 54rpx;
    height: 54rpx;
    position: absolute;
    top: -27rpx;
    right: -27rpx;
}
```

点击X图片时删除列表数组里的对应元素 js代码如下：
```js
deleteFood (index) {
    this.foodsChosen.splice(index, 1)
    this.$apply()
},
```

增加元素的代码如下：
```js
chooseFood (index) {
    let food = this.foods[index]
    this.foodsChosen.push(deepclone(food))
    this.$apply()
},
```
复现方式：
在模拟机和安卓机上能正常删除和再添加东西进列表 然而苹果6s 6P 7 会出现 多选几个食物之后，点击删除，假如删除的是第1个元素，实际上第1个元素的框框和第2个元素的X会一起消失，只留下第2个元素的框框和第1个元素的X 从而导致X的位置看起来是错位的
![image](https://cloud.githubusercontent.com/assets/16346984/25603234/782254ea-2f2c-11e7-9578-c6a3ba6efaed.png)

但是此时点击错位的第一个X又能成功删除第一个元素 猜测是脏检查遍历错误

而再次往数组里增加东西 又能恢复正确的定位
